### ISSUE TITLE
Find pycnn.so, but wrong architecture

### ISSUE THREAD

**Issue by datquocnguyen** [clab/cnn#76]
Hi,
It seems like I got pycnn built successfully. But an error of "wrong architecture" showed up when running example files. 
Do you have any idea to fix this issue?
Thank you very much.

=== pycnn$ make install ===
...
...
39 warnings generated.
++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -Wl,-F. build/temp.macosx-10.11-intel-2.7/pycnn.o -L. -L$ORIGIN/./ -lcnn_shared -o build/lib.macosx-10.11-intel-2.7/pycnn.so
ld: warning: directory not found for option '-L$ORIGIN/./'
ld: warning: ignoring file ./libcnn_shared.dylib, file was built for x86_64 which is not the architecture being linked (i386): ./libcnn_shared.dylib
ld: warning: ignoring file /opt/local/lib/gcc48/libstdc++.dylib, file was built for x86_64 which is not the architecture being linked (i386): /opt/local/lib/gcc48/libstdc++.dylib
ld: warning: ignoring file /opt/local/lib/gcc48/libgcc_ext.10.5.dylib, missing required architecture i386 in file /opt/local/lib/gcc48/libgcc_ext.10.5.dylib (1 slices)
ld: warning: ignoring file /opt/local/lib/gcc48/gcc/x86_64-apple-darwin15/4.8.5/libgcc.a, file was built for archive which is not the architecture being linked (i386): /opt/local/lib/gcc48/gcc/x86_64-apple-darwin15/4.8.5/libgcc.a
creating build/bdist.macosx-10.11-intel/egg
copying build/lib.macosx-10.11-intel-2.7/pycnn.so -> build/bdist.macosx-10.11-intel/egg
creating stub loader for pycnn.so
byte-compiling build/bdist.macosx-10.11-intel/egg/pycnn.py to pycnn.pyc
creating build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying pyCNN.egg-info/PKG-INFO -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying pyCNN.egg-info/SOURCES.txt -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying pyCNN.egg-info/dependency_links.txt -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
copying pyCNN.egg-info/top_level.txt -> build/bdist.macosx-10.11-intel/egg/EGG-INFO
writing build/bdist.macosx-10.11-intel/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist/pyCNN-0.0.0-py2.7-macosx-10.11-intel.egg' and adding 'build/bdist.macosx-10.11-intel/egg' to it
removing 'build/bdist.macosx-10.11-intel/egg' (and everything under it)
Processing pyCNN-0.0.0-py2.7-macosx-10.11-intel.egg
Removing /Users/dqnguyen/Library/Python/2.7/lib/python/site-packages/pyCNN-0.0.0-py2.7-macosx-10.11-intel.egg
Copying pyCNN-0.0.0-py2.7-macosx-10.11-intel.egg to /Users/dqnguyen/Library/Python/2.7/lib/python/site-packages
pyCNN 0.0.0 is already the active version in easy-install.pth

Installed /Users/dqnguyen/Library/Python/2.7/lib/python/site-packages/pyCNN-0.0.0-py2.7-macosx-10.11-intel.egg
Processing dependencies for pyCNN==0.0.0
Finished processing dependencies for pyCNN==0.0.0

=== pyexamples$ python xor.py ===

Traceback (most recent call last):
  File "xor.py", line 1, in <module>
    from pycnn import *
  File "build/bdist.macosx-10.11-intel/egg/pycnn.py", line 7, in <module>
  File "build/bdist.macosx-10.11-intel/egg/pycnn.py", line 6, in __bootstrap__
ImportError: dlopen(/Users/dqnguyen/.python-eggs/pyCNN-0.0.0-py2.7-macosx-10.11-intel.egg-tmp/pycnn.so, 2): no suitable image found.  Did find:
	/Users/dqnguyen/.python-eggs/pyCNN-0.0.0-py2.7-macosx-10.11-intel.egg-tmp/pycnn.so: mach-o, but wrong architecture

**Comment by datquocnguyen** [comment]
I fixed it. 
I am not sure what happened on my computer so that pycnn.so  in the directory "$PATH_TO_CNN/pycnn/" is 32-bit lib, but pycnn.so in the directory $PATH_TO_CNN/pycnn/build/lib{.*}/" is 64-bit lib. The solution is to replace the 32-bit pycnn.so by the 64-bit pycnn.so.
